#ifndef AF_H
#define AF_H

#include <vector>
#include <unordered_map>
#include <string>
#include <cstdint>     		// uncomment if boostlibs are not installed

enum task { EC, ES, UNKNOWN_TASK };
enum semantics { CO, ST, PR, UNKNOWN_SEM };

/* The following hash_combine function is from the Boost software library
 * and is subject to the following licence.
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

template <class T>
inline void hash_combine(std::size_t & seed, const T & v)
{
  std::hash<T> hasher;
  seed ^= hasher(v) + 0x9e3779b9 + (seed << 6) + (seed >> 2);
}

namespace std
{
  template<typename S, typename T> struct hash<pair<S, T>>
  {
	inline size_t operator()(const pair<S, T> & v) const
	{
	  size_t seed = 0;
	  ::hash_combine(seed, v.first);
	  ::hash_combine(seed, v.second);
	  return seed;
	}
  };
}

class AF {
public:

AF();

semantics sem;
std::string solver_path;

uint32_t args;
uint32_t count;

std::vector<std::string> int_to_arg;
std::unordered_map<std::string,uint32_t> arg_to_int;

std::vector<std::vector<uint32_t>> attackers;
std::vector<std::vector<uint32_t>> attacked;
std::vector<bool> unattacked;
std::vector<uint8_t> self_attack;
std::unordered_map<std::pair<uint32_t,uint32_t>,bool> att_exists;
std::unordered_map<std::pair<uint32_t,uint32_t>,bool> symmetric_attack;

std::vector<int> accepted_var;
std::vector<int> rejected_var;
std::vector<int> undecided_var;

void add_argument(std::string arg);
void add_attack(std::pair<std::string,std::string> att);

void initialize_attackers();
void initialize_vars();

void set_solver_path(std::string path);

};

#endif